/**
 * SKAM-ML/XML Parser Core
 *
 * Document → SKAM JSON 変換（環境非依存の共通ロジック）
 */

import type {
  SKAMDocument,
  Token,
  Block,
  Mark,
  Reading,
  Position,
  KaeriMark,
  OkuriganaMark,
  YomiganaMark,
  OkimojiMark,
  JojiMark,
  SoeganaMark,
  KutotenMark,
  IdGenerator,
  EmphasisMark,
  SaidokuMark,
  SaidokuForm,
  OkototenMark,
  TatetenMark,
  GlyphGridCoord,
  HighlightMark,
  HighlightStyle,
  RefMark,
  RefFormat,
} from '@kanbun/skam';
import { createRandomIdGenerator } from '@kanbun/skam';

// ============================================================================
// Constants
// ============================================================================

const SKAM_NS = 'urn:skam:1';

const VALID_KAERI_KINDS = [
  're',
  'ichi',
  'ni',
  'san',
  'shi',
  'jo',
  'chu',
  'ge',
  'ko',
  'otsu',
  'hei',
  'tei',
  'ten',
  'chi',
  'jin',
] as const;
type KaeriKind = (typeof VALID_KAERI_KINDS)[number];

const KAERI_VALUE_MAP: Record<KaeriKind, string> = {
  re: '\u3191',
  ichi: '\u3192',
  ni: '\u3193',
  san: '\u3194',
  shi: '\u3195',
  jo: '\u3196',
  chu: '\u3197',
  ge: '\u3198',
  ko: '\u3199',
  otsu: '\u319A',
  hei: '\u319B',
  tei: '\u319C',
  ten: '\u319D',
  chi: '\u319E',
  jin: '\u319F',
};

const VALID_HIGHLIGHT_STYLES = ['solid', 'dotted', 'dashed', 'wavy', 'double'] as const;
const VALID_REF_FORMATS = [
  'alpha-upper',
  'alpha-lower',
  'numeric-paren',
  'numeric-bracket',
  'numeric-circled',
  'iroha-katakana',
  'iroha-hiragana',
  'gojuon-katakana',
  'gojuon-hiragana',
  'kanji-numeric',
] as const;

// ============================================================================
// Position Tracking Types
// ============================================================================

/**
 * Position information in the source XML
 */
export interface PositionInfo {
  /** 1-based line number */
  line: number;
  /** 1-based column number */
  column: number;
  /** 0-based byte offset from the start of the source */
  offset: number;
}

/**
 * Token position range in the source XML
 */
export interface TokenPosition {
  /** Start position (inclusive) */
  start: PositionInfo;
  /** End position (exclusive) */
  end: PositionInfo;
}

// ============================================================================
// Error Types
// ============================================================================

export class SKAMXMLParseError extends Error {
  constructor(
    message: string,
    public readonly line?: number,
    public readonly column?: number
  ) {
    super(message);
    this.name = 'SKAMXMLParseError';
  }
}

// ============================================================================
// Position Tracker
// ============================================================================

/**
 * Tracks positions in the source XML string.
 * Handles multi-byte characters (like kanji) correctly.
 */
class PositionTracker {
  private readonly source: string;
  private readonly lineStarts: number[];

  constructor(source: string) {
    this.source = source;
    this.lineStarts = this.computeLineStarts(source);
  }

  private computeLineStarts(source: string): number[] {
    const starts = [0];
    for (let i = 0; i < source.length; i++) {
      if (source[i] === '\n') {
        starts.push(i + 1);
      }
    }
    return starts;
  }

  /**
   * Convert character offset to PositionInfo
   */
  offsetToPosition(offset: number): PositionInfo {
    // Binary search for line number
    let low = 0;
    let high = this.lineStarts.length - 1;
    while (low < high) {
      const mid = Math.ceil((low + high) / 2);
      if (this.lineStarts[mid]! <= offset) {
        low = mid;
      } else {
        high = mid - 1;
      }
    }
    const line = low + 1; // 1-based
    const column = offset - this.lineStarts[low]! + 1; // 1-based
    return { line, column, offset };
  }

  /**
   * Find position of text starting from a given offset
   */
  findText(text: string, startOffset: number): number {
    return this.source.indexOf(text, startOffset);
  }

  /**
   * Get byte offset for a character offset (handles multi-byte UTF-8)
   */
  getByteOffset(charOffset: number): number {
    const encoder = new TextEncoder();
    const bytes = encoder.encode(this.source.slice(0, charOffset));
    return bytes.length;
  }

  getSource(): string {
    return this.source;
  }
}

// ============================================================================
// Parser State
// ============================================================================

interface ParserState {
  tokens: Token[];
  blocks: Block[];
  marks: Mark[];
  readings: Reading[];
  noteContents: Map<string, string>;
  autoGeneratedIds: Set<string>;
  currentBlockId: string | null;
  positionTracker: PositionTracker | null;
  /** Current search offset in the source for position tracking */
  currentSearchOffset: number;
  idGenerator: IdGenerator;
}

function createParserState(source?: string, idGenerator?: IdGenerator): ParserState {
  return {
    tokens: [],
    blocks: [],
    marks: [],
    readings: [],
    noteContents: new Map(),
    autoGeneratedIds: new Set(),
    currentBlockId: null,
    positionTracker: source ? new PositionTracker(source) : null,
    currentSearchOffset: 0,
    idGenerator: idGenerator ?? createRandomIdGenerator(),
  };
}

// ============================================================================
// Utility Functions
// ============================================================================

function getAttr(element: Element, name: string): string | null {
  return element.getAttribute(name);
}

function getRequiredAttr(element: Element, name: string, elementName: string): string {
  // Note: @xmldom/xmldom returns "" for missing attributes, not null
  // We need to check hasAttribute to properly detect missing attributes
  if (!element.hasAttribute(name)) {
    throw new SKAMXMLParseError(`Missing required attribute '${name}' on <${elementName}>`);
  }
  const value = element.getAttribute(name);
  if (value === null || value === '') {
    throw new SKAMXMLParseError(`Missing required attribute '${name}' on <${elementName}>`);
  }
  return value;
}

function isElement(node: Node): node is Element {
  return node.nodeType === 1; // Node.ELEMENT_NODE
}

function isText(node: Node): node is Text {
  return node.nodeType === 3; // Node.TEXT_NODE
}

function getLocalName(element: Element): string {
  return element.localName ?? element.nodeName.split(':').pop() ?? '';
}

function generateTokenId(state: ParserState): string {
  const id = state.idGenerator.generate('t');
  state.autoGeneratedIds.add(id);
  return id;
}

function generateMarkId(state: ParserState): string {
  const id = state.idGenerator.generate('m');
  state.autoGeneratedIds.add(id);
  return id;
}

// ============================================================================
// Token Generation
// ============================================================================

function addTokensFromText(text: string, state: ParserState): string[] {
  const ids: string[] = [];
  const tracker = state.positionTracker;

  // Split by grapheme clusters (simplified: by character)
  for (const char of text) {
    if (/\s/.test(char)) {
      // Skip whitespace but update search offset if tracking
      if (tracker) {
        const pos = tracker.findText(char, state.currentSearchOffset);
        if (pos !== -1) {
          state.currentSearchOffset = pos + char.length;
        }
      }
      continue;
    }

    const id = generateTokenId(state);
    const token: Token = { id, text: char };

    // Add position info if tracking is enabled
    if (tracker) {
      const charPos = tracker.findText(char, state.currentSearchOffset);
      if (charPos !== -1) {
        const startPos = tracker.offsetToPosition(charPos);
        const endPos = tracker.offsetToPosition(charPos + char.length);

        // Convert to byte offsets for the offset field
        const startByteOffset = tracker.getByteOffset(charPos);
        const endByteOffset = tracker.getByteOffset(charPos + char.length);

        const position: TokenPosition = {
          start: { ...startPos, offset: startByteOffset },
          end: { ...endPos, offset: endByteOffset },
        };

        token.ext = { ...token.ext, position };
        state.currentSearchOffset = charPos + char.length;
      }
    }

    state.tokens.push(token);
    ids.push(id);
  }
  return ids;
}

function createAnchor(tokenIds: string[]): { from: string; to: string } {
  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('Cannot create anchor from empty token list');
  }
  return { from: tokenIds[0]!, to: tokenIds[tokenIds.length - 1]! };
}

// ============================================================================
// Mark Processors
// ============================================================================

function parseKaeriKind(kind: string): string {
  // 単一返り点
  if (VALID_KAERI_KINDS.includes(kind as KaeriKind)) {
    return KAERI_VALUE_MAP[kind as KaeriKind];
  }

  // 複合返り点（例: ichi-re → 一レ）
  const parts = kind.split('-');
  if (parts.length > 1 && parts.every((p) => VALID_KAERI_KINDS.includes(p as KaeriKind))) {
    return parts.map((p) => KAERI_VALUE_MAP[p as KaeriKind]).join('');
  }

  throw new SKAMXMLParseError(
    `Invalid kaeri kind '${kind}'. Valid kinds: ${VALID_KAERI_KINDS.join(', ')} (compound: e.g. ichi-re)`
  );
}

function processKaeri(element: Element, state: ParserState, precedingTokenId: string | null): void {
  const kind = getRequiredAttr(element, 'kind', 'skam:kaeri');
  const value = parseKaeriKind(kind);

  if (!precedingTokenId) {
    throw new SKAMXMLParseError('<skam:kaeri> requires a preceding token');
  }

  const mark: KaeriMark = {
    type: 'kaeri',
    id: generateMarkId(state),
    position: { blockId: state.currentBlockId!, after: precedingTokenId },
    value,
  };

  state.marks.push(mark);
}

function processKun(element: Element, state: ParserState): string[] {
  const yomi = getAttr(element, 'yomi');
  const okuri = getAttr(element, 'okuri');
  const soe = getAttr(element, 'soe');

  // Extract text content and generate tokens
  const textContent = element.textContent ?? '';
  const tokenIds = addTokensFromText(textContent, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:kun> must contain text');
  }

  const anchor = createAnchor(tokenIds);

  if (yomi) {
    const yomiganaMark: YomiganaMark = {
      type: 'yomigana',
      id: generateMarkId(state),
      anchor,
      value: yomi,
    };
    state.marks.push(yomiganaMark);
  }

  if (okuri) {
    const okuriganaMark: OkuriganaMark = {
      type: 'okurigana',
      id: generateMarkId(state),
      anchor,
      value: okuri,
    };
    state.marks.push(okuriganaMark);
  }

  if (soe) {
    const soeganaMark: SoeganaMark = {
      type: 'soegana',
      id: generateMarkId(state),
      anchor,
      value: soe,
    };
    state.marks.push(soeganaMark);
  }

  return tokenIds;
}

function processYomigana(element: Element, state: ParserState): string[] {
  const value = getRequiredAttr(element, 'value', 'skam:yomigana');

  const textContent = element.textContent ?? '';
  const tokenIds = addTokensFromText(textContent, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:yomigana> must contain text');
  }

  const mark: YomiganaMark = {
    type: 'yomigana',
    id: generateMarkId(state),
    anchor: createAnchor(tokenIds),
    value,
  };

  state.marks.push(mark);
  return tokenIds;
}

function processKutoten(
  element: Element,
  state: ParserState,
  precedingTokenId: string | null
): void {
  const value = getRequiredAttr(element, 'value', 'skam:kutoten');
  const kind = getAttr(element, 'kind') as 'ku' | 'ten' | 'other' | null;

  // Position includes blockId and optional after
  // - { blockId, after: tokenId } - after the specified token
  // - { blockId } - at block start (no preceding token)
  const position: Position = precedingTokenId
    ? { blockId: state.currentBlockId!, after: precedingTokenId }
    : { blockId: state.currentBlockId! };

  const mark: KutotenMark = {
    type: 'kutoten',
    id: generateMarkId(state),
    position,
    value,
  };

  if (kind) {
    mark.kind = kind;
  }

  state.marks.push(mark);
}

function processOkototen(element: Element, state: ParserState): string[] {
  const grid = getRequiredAttr(element, 'grid', 'skam:okototen');
  const xStr = getRequiredAttr(element, 'x', 'skam:okototen');
  const yStr = getRequiredAttr(element, 'y', 'skam:okototen');
  const shape = getRequiredAttr(element, 'shape', 'skam:okototen');
  const sound = getAttr(element, 'sound');
  const color = getAttr(element, 'color');

  // Validate grid format
  if (!/^\d+x\d+$/.test(grid)) {
    throw new SKAMXMLParseError(
      `Invalid grid format '${grid}'. Expected format: NxN (e.g., '5x5')`
    );
  }

  const x = parseInt(xStr, 10);
  const y = parseInt(yStr, 10);

  if (Number.isNaN(x) || Number.isNaN(y)) {
    throw new SKAMXMLParseError('x and y must be integers');
  }

  const textContent = element.textContent ?? '';
  const tokenIds = addTokensFromText(textContent, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:okototen> must contain text');
  }

  const position: GlyphGridCoord = {
    system: 'glyph-grid',
    grid,
    x,
    y,
  };

  const mark: OkototenMark = {
    type: 'okototen',
    id: generateMarkId(state),
    anchor: createAnchor(tokenIds),
    position,
    shape,
  };

  if (sound) {
    mark.sound = sound;
  }

  if (color) {
    mark.color = color;
  }

  state.marks.push(mark);
  return tokenIds;
}

function processOkimoji(element: Element, state: ParserState): string[] {
  const textContent = element.textContent ?? '';
  const tokenIds = addTokensFromText(textContent, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:okimoji> must contain text');
  }

  const mark: OkimojiMark = {
    type: 'okimoji',
    id: generateMarkId(state),
    anchor: createAnchor(tokenIds),
  };

  state.marks.push(mark);
  return tokenIds;
}

function processJoji(element: Element, state: ParserState): string[] {
  const textContent = element.textContent ?? '';
  const tokenIds = addTokensFromText(textContent, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:joji> must contain text');
  }

  const mark: JojiMark = {
    type: 'joji',
    id: generateMarkId(state),
    anchor: createAnchor(tokenIds),
  };

  state.marks.push(mark);
  return tokenIds;
}

function processSoegana(element: Element, state: ParserState): string[] {
  const value = getRequiredAttr(element, 'value', 'skam:soegana');

  // Extract text content (the wrapped character) and generate tokens
  const textContent = element.textContent ?? '';
  const tokenIds = addTokensFromText(textContent, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:soegana> must contain text (the character to annotate)');
  }

  const mark: SoeganaMark = {
    type: 'soegana',
    id: generateMarkId(state),
    anchor: createAnchor(tokenIds),
    value,
  };

  state.marks.push(mark);
  return tokenIds;
}

function processSpan(element: Element, state: ParserState): string[] {
  const type = getRequiredAttr(element, 'type', 'skam:span');
  const styleAttr = getAttr(element, 'style');

  // Track marks count before processing to find refs added during span processing
  const marksCountBefore = state.marks.length;

  // Process children to get tokens
  const tokenIds = processBlockChildren(element, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:span> must contain content');
  }

  // Find refs added during this span's processing
  const refsAddedInSpan = state.marks
    .slice(marksCountBefore)
    .filter((m): m is RefMark => m.type === 'ref');

  if (type === 'emphasis') {
    const mark: EmphasisMark = {
      type: 'emphasis',
      id: generateMarkId(state),
      anchor: createAnchor(tokenIds),
    };

    // style は CSS text-emphasis-style の値（任意の文字列も可）
    if (styleAttr) {
      mark.style = styleAttr;
    }

    state.marks.push(mark);
  } else if (type === 'highlight') {
    const refAttr = getAttr(element, 'ref');

    const mark: HighlightMark = {
      type: 'highlight',
      id: generateMarkId(state),
      anchor: createAnchor(tokenIds),
    };

    if (styleAttr) {
      if (!VALID_HIGHLIGHT_STYLES.includes(styleAttr as (typeof VALID_HIGHLIGHT_STYLES)[number])) {
        throw new SKAMXMLParseError(
          `Invalid highlight style '${styleAttr}'. Valid styles: ${VALID_HIGHLIGHT_STYLES.join(', ')}`
        );
      }
      mark.style = styleAttr as HighlightStyle;
    }

    if (refAttr) {
      // highlight.ref が指定されている場合
      // 指定されたidを持つrefが既に存在するかチェック
      const existingRefWithId = state.marks.find(
        (m): m is RefMark => m.type === 'ref' && m.id === refAttr
      );

      if (existingRefWithId) {
        // 明示的な対応関係
        mark.ref = refAttr;
      } else if (refsAddedInSpan.length === 1) {
        // highlight.ref あり + 内部refが1つ + 指定idのrefが存在しない
        const singleRef = refsAddedInSpan[0]!;
        const hasExplicitId = singleRef.id && !state.autoGeneratedIds.has(singleRef.id);
        if (!hasExplicitId) {
          // ref.id がない → エラー
          throw new SKAMXMLParseError(
            `<skam:span type="highlight" ref="${refAttr}"> references a ref that does not exist. ` +
              `Add xml:id="${refAttr}" to the <skam:ref> element inside the span.`
          );
        } else {
          // ref.id あり → 対応しない、highlight.refはそのまま設定
          mark.ref = refAttr;
        }
      } else {
        // 内部refが複数 → 単独表示、highlight.refはそのまま設定
        mark.ref = refAttr;
      }
    } else if (refsAddedInSpan.length === 1) {
      // highlight.ref なし + 内部refが1つ → 対応関係
      const singleRef = refsAddedInSpan[0]!;
      if (singleRef.id) {
        mark.ref = singleRef.id;
      }
    }
    // highlight.ref なし + 内部refが複数 + すべてid指定あり → 単独表示（何もしない）

    state.marks.push(mark);
  }

  return tokenIds;
}

function processTateten(element: Element, state: ParserState): string[] {
  // Process children recursively to handle inner elements like <skam:kaeri>
  const tokenIds = processBlockChildren(element, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:tateten> must contain text');
  }

  const mark: TatetenMark = {
    type: 'tateten',
    id: generateMarkId(state),
    anchor: createAnchor(tokenIds),
  };

  state.marks.push(mark);
  return tokenIds;
}

function processSaidoku(element: Element, state: ParserState): string[] {
  let baseElement: Element | null = null;
  const kunforms: Element[] = [];

  // Find base and kunform elements
  for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    if (!child || !isElement(child)) continue;

    const localName = getLocalName(child);
    if (localName === 'base') {
      baseElement = child;
    } else if (localName === 'kunform') {
      kunforms.push(child);
    }
  }

  if (!baseElement) {
    throw new SKAMXMLParseError('<skam:saidoku> requires <skam:base> element');
  }

  if (kunforms.length === 0) {
    throw new SKAMXMLParseError('<skam:saidoku> requires at least one <skam:kunform> element');
  }

  // Generate tokens from base
  const baseText = baseElement.textContent ?? '';
  const tokenIds = addTokensFromText(baseText, state);

  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:base> must contain text');
  }

  // Build forms array
  const forms: SaidokuForm[] = kunforms.map((kunform) => {
    const form: SaidokuForm = {};
    const nAttr = getAttr(kunform, 'n');
    const yomi = getAttr(kunform, 'yomi');
    const okuri = getAttr(kunform, 'okuri');

    if (nAttr) {
      form.n = parseInt(nAttr, 10);
    }
    if (yomi) {
      form.yomi = yomi;
    }
    if (okuri) {
      form.okuri = okuri;
    }

    return form;
  });

  const mark: SaidokuMark = {
    type: 'saidoku',
    id: generateMarkId(state),
    anchor: createAnchor(tokenIds),
    forms,
  };

  state.marks.push(mark);
  return tokenIds;
}

/**
 * Process skam:ref element (position-based mark)
 *
 * Supports:
 * - Empty element with format/label for auto-numbering
 * - Element with content for inline annotation (content stored in content field, not tokenized)
 * - xml:id for separated note content (note references this ref)
 *
 * Position-based: ref does not create tokens, just marks a position between tokens
 */
function processRef(element: Element, state: ParserState, precedingTokenId: string | null): void {
  const labelAttr = getAttr(element, 'label');
  const formatAttr = getAttr(element, 'format');
  // xml:id attribute takes precedence for explicit id assignment
  const xmlIdAttr = getAttr(element, 'xml:id') || getAttr(element, 'id');

  // Check for text content - this becomes the content field, not tokens
  let content: string | undefined;
  const textContent = (element.textContent ?? '').trim();

  // If element has text content but no child elements, it's inline content
  let hasChildElements = false;
  for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    if (child && isElement(child)) {
      hasChildElements = true;
      break;
    }
  }

  if (textContent && !hasChildElements) {
    content = textContent;
  }

  // Validate: label and format are mutually exclusive
  if (labelAttr && formatAttr) {
    throw new SKAMXMLParseError(
      '<skam:ref> cannot have both label and format (mutually exclusive)'
    );
  }

  // Validate: at least one of label, format, content, or xml:id (for separated definition) must be present
  if (!labelAttr && !formatAttr && !content && !xmlIdAttr) {
    throw new SKAMXMLParseError(
      '<skam:ref> requires at least one of: label, format, content, or xml:id'
    );
  }

  // Validate format value
  if (formatAttr && !VALID_REF_FORMATS.includes(formatAttr as (typeof VALID_REF_FORMATS)[number])) {
    throw new SKAMXMLParseError(
      `Invalid ref format '${formatAttr}'. Valid formats: ${VALID_REF_FORMATS.join(', ')}`
    );
  }

  // Position includes blockId and optional after
  // - { blockId, after: tokenId } - after the specified token
  // - { blockId } - at block start (no preceding token)
  const position: Position = precedingTokenId
    ? { blockId: state.currentBlockId!, after: precedingTokenId }
    : { blockId: state.currentBlockId! };

  const mark: RefMark = {
    type: 'ref',
    id: xmlIdAttr || generateMarkId(state),
    position,
  };

  if (labelAttr) {
    mark.label = labelAttr;
  }

  if (formatAttr) {
    mark.format = formatAttr as RefFormat;
  }

  if (content) {
    mark.content = content;
  }

  // Note: separated note content is resolved in processNotes()
  // The note element references this ref via its 'ref' attribute

  state.marks.push(mark);
}

// ============================================================================
// Block Processing
// ============================================================================

/**
 * Pending position-based mark that needs position assignment after tokens are known
 */
interface PendingPositionMark {
  element: Element;
  type: 'kutoten' | 'ref';
  /** Token index before this mark (-1 if at beginning) */
  precedingTokenIndex: number;
}

function processBlockChildren(element: Element, state: ParserState): string[] {
  const allTokenIds: string[] = [];
  const pendingPositionMarks: PendingPositionMark[] = [];
  let lastTokenId: string | null =
    state.tokens.length > 0 ? state.tokens[state.tokens.length - 1]!.id : null;

  for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    if (!child) continue;

    if (isText(child)) {
      const text = child.textContent ?? '';
      const ids = addTokensFromText(text, state);
      allTokenIds.push(...ids);
      if (ids.length > 0) {
        lastTokenId = ids[ids.length - 1]!;
      }
    } else if (isElement(child)) {
      const localName = getLocalName(child);

      switch (localName) {
        case 'kaeri':
          processKaeri(child, state, lastTokenId);
          break;
        case 'kun': {
          const ids = processKun(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'yomigana': {
          const ids = processYomigana(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'kutoten':
          // Defer to ensure precedingTokenIndex is within current block
          pendingPositionMarks.push({
            element: child,
            type: 'kutoten',
            precedingTokenIndex: allTokenIds.length - 1,
          });
          break;
        case 'okototen': {
          const ids = processOkototen(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'okimoji': {
          const ids = processOkimoji(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'joji': {
          const ids = processJoji(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'soegana': {
          const ids = processSoegana(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'span': {
          const ids = processSpan(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'tateten': {
          const ids = processTateten(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'saidoku': {
          const ids = processSaidoku(child, state);
          allTokenIds.push(...ids);
          if (ids.length > 0) lastTokenId = ids[ids.length - 1]!;
          break;
        }
        case 'ref':
          // Defer to ensure precedingTokenIndex is within current block
          pendingPositionMarks.push({
            element: child,
            type: 'ref',
            precedingTokenIndex: allTokenIds.length - 1,
          });
          break;
        default:
          // Unknown elements are ignored per spec
          break;
      }
    }
  }

  // Process pending position-based marks now that we have all token IDs
  for (const pending of pendingPositionMarks) {
    const precedingTokenId =
      pending.precedingTokenIndex >= 0 ? (allTokenIds[pending.precedingTokenIndex] ?? null) : null;

    if (pending.type === 'kutoten') {
      processKutoten(pending.element, state, precedingTokenId);
    } else {
      processRef(pending.element, state, precedingTokenId);
    }
  }

  return allTokenIds;
}

function processBlock(element: Element, state: ParserState): void {
  // Read xml:id attribute, or auto-generate block ID
  const xmlIdAttr = getAttr(element, 'xml:id') || getAttr(element, 'id');
  const blockId =
    xmlIdAttr ||
    (() => {
      const id = state.idGenerator.generate('b');
      state.autoGeneratedIds.add(id);
      return id;
    })();

  // Set current block ID for marks (kutoten/ref position) created within this block
  state.currentBlockId = blockId;

  const tokenIds = processBlockChildren(element, state);

  // Clear current block ID
  state.currentBlockId = null;

  // Validate non-empty block
  if (tokenIds.length === 0) {
    throw new SKAMXMLParseError('<skam:block> must contain at least one token');
  }

  // Build Block object and add to state
  const block: Block = { id: blockId, tokenIds };
  state.blocks.push(block);
}

// ============================================================================
// Document Structure Processing
// ============================================================================

function processBody(element: Element, state: ParserState): void {
  for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    if (!child) continue;

    if (isElement(child) && getLocalName(child) === 'block') {
      processBlock(child, state);
    }
  }
}

function processReadings(element: Element, state: ParserState): void {
  for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    if (!child) continue;

    if (isElement(child) && getLocalName(child) === 'reading') {
      const kind = getRequiredAttr(child, 'kind', 'skam:reading');
      const text = (child.textContent ?? '').trim();

      state.readings.push({
        kind: kind as 'kundoku' | 'kakikudashi' | 'yomiage',
        text,
      });
    }
  }
}

function processNotes(element: Element, state: ParserState): void {
  for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    if (!child) continue;

    if (isElement(child)) {
      const localName = getLocalName(child);
      // skam:note element with ref attribute referencing a skam:ref element
      if (localName === 'note') {
        // Note: @xmldom/xmldom returns "" for missing attributes, not null
        // Use || instead of ?? to handle empty string fallback
        // New design: note has 'ref' attribute that references skam:ref's xml:id
        const refAttr = getAttr(child, 'ref');
        if (refAttr) {
          const text = (child.textContent ?? '').trim();
          state.noteContents.set(refAttr, text);
        }
      }
    }
  }
}

function resolveContentReferences(state: ParserState): void {
  // New design: note's ref attribute references skam:ref's id
  // Find ref marks and resolve their content from noteContents
  for (const mark of state.marks) {
    if (mark.type === 'ref' && mark.id) {
      const noteText = state.noteContents.get(mark.id);
      if (noteText !== undefined) {
        (mark as RefMark).content = noteText;
      }
    }
  }
}

// ============================================================================
// Main Parse Function (from Document)
// ============================================================================

export interface ParseOptions {
  /** Validate the resulting document (default: true) */
  validate?: boolean;
  /** Enable position tracking in token.ext (default: false) */
  trackPositions?: boolean;
  /** Custom ID generator for token/mark/block IDs */
  idGenerator?: IdGenerator;
}

/**
 * Parse SKAM-ML Document to SKAMDocument
 *
 * @param doc Parsed XML Document
 * @param options Parse options
 * @param source Original XML source string (required for position tracking)
 * @returns SKAMDocument
 * @throws SKAMXMLParseError if parsing fails
 */
export function parseFromDocument(
  doc: Document,
  options: ParseOptions = {},
  source?: string
): SKAMDocument {
  const { validate: _validate = true, trackPositions = false, idGenerator } = options;

  // Get root element
  const root = doc.documentElement;
  if (!root) {
    throw new SKAMXMLParseError('Empty document');
  }

  // Validate namespace
  const rootLocalName = getLocalName(root);
  const ns = root.namespaceURI ?? root.getAttribute('xmlns:skam');

  if (rootLocalName !== 'doc' || (ns !== SKAM_NS && !root.getAttribute('xmlns:skam'))) {
    throw new SKAMXMLParseError(
      `Invalid root element. Expected <skam:doc xmlns:skam="${SKAM_NS}"> but got <${root.tagName}>`
    );
  }

  // Initialize state (with source for position tracking if enabled)
  const state = createParserState(trackPositions ? source : undefined, idGenerator);

  // Find and process main sections
  let hasBody = false;

  for (let i = 0; i < root.childNodes.length; i++) {
    const child = root.childNodes[i];
    if (!child || !isElement(child)) continue;

    const localName = getLocalName(child);

    switch (localName) {
      case 'meta':
        // Currently we just ignore meta, tokenization is always 'char'
        break;
      case 'body':
        hasBody = true;
        processBody(child, state);
        break;
      case 'readings':
        processReadings(child, state);
        break;
      case 'notes':
        processNotes(child, state);
        break;
    }
  }

  if (!hasBody) {
    throw new SKAMXMLParseError('Document must contain <skam:body>');
  }

  // Resolve content references for ref marks
  resolveContentReferences(state);

  // Build document
  const skamDoc: SKAMDocument = {
    format: 'skam@0.1',
    tokens: state.tokens,
    blocks: state.blocks,
    marks: state.marks,
    readings: state.readings,
  };

  return skamDoc;
}
